export default {
  CART_AMOUNT_INCREAMENT: 'CART_AMOUNT_INCREAMENT',
  CART_AMOUNT_DECREAMENT: 'CART_AMOUNT_DECREAMENT',
  CHANGE_BLOG_LOADING: 'CHANGE_BLOG_LOADING',
  START_FETCH_BLOG_LIST: 'START_FETCH_BLOG_LIST',
  FETCH_BLOG_LIST_SUCESS: 'FETCH_BLOG_LIST_SUCESS',
  FETCH_BLOG_LIST_FAILED: 'FETCH_BLOG_LIST_FAILED',
}